- omegaconf/config.py
- omegaconf/omegaconf.py
- tests/test_base_config.py
> fixed a bug causing improper restoration of struct flag in some cases

- omegaconf/config.py
- tests/test_update.py
> Allowing = in dotlist override value

- omegaconf/listconfig.py
- tests/test_basic_ops_list.py
> Implemented + operator for ListConfig

- news/37.feature
- omegaconf/omegaconf.py
- tests/test_serialization.py
- tests/test_serialization_deprecated_save.py
> Add resolve flag to OmegaConf.save()

- news/40.bugfix
- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
> fixed error expanding an DictConfig in pycharm debugger

- docs/source/usage.rst
- news/42.feature
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/test_basic_ops_dict.py
- tests/test_readonly.py
> Implemented masked_copy

- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- tests/test_base_config.py
- tests/test_basic_ops_list.py
> Improved shallow copy support and added DictConfig.copy()

- .circleci/config.yml
- .coveragerc
- news/88.removal
- noxfile.py
- omegaconf/__init__.py
- omegaconf/config.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- omegaconf/version.py
- setup.py
> Dropped Python 2.7 support

- .isort.cfg
- .pre-commit-config.yaml
- news/105.feature
- news/107.feature
- noxfile.py
- omegaconf/__init__.py
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/nodes.py
- omegaconf/omegaconf.py
- setup.py
- tests/examples/test_dataclass_example.py
- tests/structured_conf/attr_test_data.py
- tests/structured_conf/dataclass_test_data.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_create.py
- tests/test_interpolation.py
- tests/test_merge.py
- tests/test_nodes.py
- tests/test_readonly.py
- tests/test_serialization.py
- tests/test_serialization_deprecated_save.py
- tests/test_struct.py
- tests/test_structured_config.py
- tests/test_update.py
- tests/test_utils.py
> Using isort to sort imports

- .pre-commit-config.yaml
- CONTRIBUTING.md
- docs/source/usage.rst
- news/94.bugfix
- omegaconf/dictconfig.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_nodes.py
- tests/test_struct.py
In struct mode, accessing a missing key now raises AttributeError and not key error
> strucd mode invalid access -> AttributeError

- news/124.bugfix
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- tests/structured_conf/test_config_eq.py
> Fix eq fails if object contains unresolveable values

- news/127.bugfix
- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
> fixed DictConfig pop

- docs/source/conf.py
- news/139.feature
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
- tests/test_base_config.py
> support Dict and List with MISSING value (???)

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/test_config_eq.py
- tests/test_merge.py
Merging a structured type into an incompatible type now raises a validation error
> Structured assignment

- docs/notebook/Tutorial.ipynb
- docs/source/structured_config.rst
- docs/source/usage.rst
- news/161.feature
- news/161.removal
- omegaconf/base.py
- omegaconf/basecontainer.py
- tests/examples/test_dataclass_example.py
- tests/test_basic_ops_dict.py
> pretty() preseves insertion order by default

- docs/notebook/Tutorial.ipynb
- docs/source/env_default_interpolation.yaml
- docs/source/usage.rst
- omegaconf/omegaconf.py
- tests/test_interpolation.py
Proposal for a solution for #170
> Optional default value for env resolver.

- news/14.bugfix
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/omegaconf.py
- tests/examples/test_dataclass_example.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_create.py
- tests/test_get_full_key.py
- tests/test_interpolation.py
- tests/test_select.py
> Various fixes + fixing #14

- docs/source/usage.rst
- news/116.removal.1
- news/116.removal.2
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_errors.py
- tests/test_get_full_key.py
- tests/test_interpolation.py
- tests/test_matrix.py
- tests/test_nodes.py
- tests/test_readonly.py
- tests/test_select.py
- tests/test_update.py
- tests/test_utils.py
> Deprecated select and update (move both from BaseContainer to to OmegaConf)

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/nodes.py
- tests/structured_conf/test_structured_basic.py
- tests/test_base_config.py
- tests/test_errors.py
- tests/test_struct.py
cc @jrapin
Fixing both issues you reported.
> Several structured configs fixes

- omegaconf/_utils.py
- omegaconf/omegaconf.py
- tests/__init__.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
- tests/test_errors.py
- tests/test_utils.py
> Union error

- omegaconf/_utils.py
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
> List iterate

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/errors.py
- tests/test_errors.py
> fixed cases where exception messages were duplicated

- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
> fixes pop with struct mode

- omegaconf/_utils.py
- tests/test_interpolation.py
- tests/test_utils.py
> correctly detecting interpolation if value has a /

- .coveragerc
- omegaconf/_utils.py
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_basic.py
- tests/structured_conf/test_structured_config.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_create.py
- tests/test_errors.py
- tests/test_get_full_key.py
- tests/test_omegaconf.py
- tests/test_utils.py
> Simplified and improved ref_type handling and error reporting

- omegaconf/base.py
- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
- tests/test_errors.py
> Struct mode not supports del and pop

- omegaconf/basecontainer.py
- tests/test_base_config.py
> To container fixes #2

- omegaconf/dictconfig.py
- omegaconf/nodes.py
- tests/__init__.py
- tests/test_errors.py
> improved invalid enum error messages

- news/253.bugfix
- omegaconf/omegaconf.py
> Relax save and load APIs to accept IO[Any]

- docs/source/structured_config.rst
> Fix a typo

- news/260.bugfix
- omegaconf/omegaconf.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
> Fix a big initializing a Structured Config with "var : Any = Nested()"

- .pre-commit-config.yaml
- docs/source/structured_config.rst
- docs/source/usage.rst
- news/279.bugfix
- omegaconf/_utils.py
- omegaconf/omegaconf.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
Tuple weren't checked when creating from a dataclass. 
Added additional tests so it covers optional lists and optional tuples.
> Fix #279 bug optional tuple.

- news/291.bug
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_basic.py
- tests/structured_conf/test_structured_config.py
- tests/test_errors.py
- tests/test_matrix.py
1. Improves error messages in some cases
2. Closes #291
3. Closes #293
> Fixes multiple bugs

- .pre-commit-config.yaml
precommit and requirements/dev.txt isort didn't match
> isort version 5.0.9

- news/287.bugfix
- omegaconf/omegaconf.py
- tests/__init__.py
- tests/test_serialization.py
Closes #287 .
Added test.
Added news.
> OmegaConf.save() not accepting dataclasses fix

- news/310.bugfix
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- tests/__init__.py
- tests/test_merge.py
> Fix error when merging a structured config into a field with None value

- docs/notebook/Tutorial.ipynb
- news/263.removal
- omegaconf/omegaconf.py
> Revert to resolve=False to_yaml()

- news/332.bugfix
- omegaconf/_utils.py
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/nodes.py
- omegaconf/omegaconf.py
- tests/test_basic_ops_dict.py
> Remove dot-keys usage warning

- news/283.bugfix
- omegaconf/base.py
- tests/test_interpolation.py
> Support indirect interpolation

- news/304.bugfix
- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
> Fix DictConfig setdefault method to behave as it should

- news/348.bugfix
- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_list.py
- tests/test_errors.py
- tests/test_merge.py
> Fixed merge of list with dicts into list with dataclasses if they are compatible

- news/350.bugfix
- omegaconf/omegaconf.py
- tests/test_to_yaml.py
> OmegaConf.to_yaml() now properly support Structured Configs

- docs/source/index.rst
- docs/source/usage.rst
- news/278.docs
- omegaconf/omegaconf.py
- tests/test_serialization.py
> Documented serialization APIs

- docs/source/structured_config.rst
- docs/source/usage.rst
- news/286.docs
- news/343.docs
> Docs improvements

- news/358.bugfix
- omegaconf/basecontainer.py
- tests/test_to_yaml.py
> Fix cfg.pretty() deprecation warning

- news/360.bugfix
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_config.py
- tests/test_merge.py
- tests/test_update.py
> OmegaConf.update should merge dicts/lists instead of assigning them.

- docs/source/usage.rst
We need a blank line before a `doctest` statement
> Minor doc fix

- docs/source/usage.rst
- news/360.bugfix
- news/363.feature
- news/363.removal
- omegaconf/basecontainer.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_config.py
- tests/test_errors.py
- tests/test_readonly.py
- tests/test_update.py
> OmegaConf.update() now takes a merge flag to indicate merge or set config values

- news/48.feature
- omegaconf/base.py
- omegaconf/errors.py
- omegaconf/version.py
- tests/test_interpolation.py
Initial stab at relative interpolation
Closes #48
> Relative interpolation support

- omegaconf/base.py
- tests/test_interpolation.py
> Fix issue when resolver arg starts with a dot

- docs/source/usage.rst
- news/228.api_change
- news/228.feature
- omegaconf/basecontainer.py
- omegaconf/omegaconf.py
- pyproject.toml
- tests/test_select.py
> OmegaConf.select() now takes an optional default value to return if a key is not found

- news/378.bugfix
- news/379.bugfix
- omegaconf/_utils.py
- omegaconf/base.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_dict.py
- tests/test_utils.py
> Fixes forward declaration in List and Dict

- news/398.feature
- omegaconf/basecontainer.py
- omegaconf/omegaconf.py
- tests/test_base_config.py
> flag to not convert Structured Configs in to_container()

- news/403.bugfix
- omegaconf/omegaconf.py
- tests/test_serialization.py
> Fix loading of an empty file via a file-pointer to return an empty dict

- news/412.api_change
- omegaconf/_utils.py
- tests/structured_conf/test_structured_config.py
> deprecating auto expansion of nested dataclasses without default value

- .circleci/config.yml
- CONTRIBUTING.md
- news/447.feature
- noxfile.py
- setup.py
> Python 3.9 support

- omegaconf/_utils.py
- tests/test_interpolation.py
cc @odelalleau : I am expecting this to work with the new interpolation support but fyi.
> Support for interpolation where the key has @ symbol

- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/nodes.py
- tests/__init__.py
- tests/test_create.py
Attempting to solve https://github.com/facebookresearch/hydra/issues/1199
@ppwwyyxx, please try with this version of OmegaConf and tell if if you see anything else.
> allow_objects: support non-copyable objects

- news/449.bugfix
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- tests/test_basic_ops_dict.py
> Fixed assigment of container to itself

- omegaconf/basecontainer.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_basic.py
- tests/test_merge.py
As discussed in https://github.com/omry/omegaconf/pull/463#discussion_r545868699
> Fix edge case when merging a missing structured config

- .pre-commit-config.yaml
- .stubs/pytest.pyi
- requirements/dev.txt
- tests/conftest.py
- tests/examples/test_postponed_annotations.py
- tests/structured_conf/test_structured_config.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_config_eq.py
- tests/test_create.py
- tests/test_errors.py
- tests/test_get_full_key.py
- tests/test_interpolation.py
- tests/test_merge.py
- tests/test_nodes.py
- tests/test_omegaconf.py
- tests/test_readonly.py
- tests/test_select.py
- tests/test_serialization.py
- tests/test_struct.py
- tests/test_to_yaml.py
- tests/test_update.py
- tests/test_utils.py
1. upgrade to mypy 0.790
2. Removing pytest srub
3. remove type: ignore from all pytest parameterized tests.
> strict mypy for tests

- news/492.api_change
- omegaconf/base.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- omegaconf/nodes.py
- requirements/dev.txt
- tests/__init__.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_create.py
- tests/test_interpolation.py
Updates per the feedback on #481 
Closes #492
> 481 feedback

- omegaconf/base.py
- tests/test_serialization.py
> Fix flags cache inconsistency when serializing a container

- docs/source/structured_config.rst
* Improve docs regarding interpolations in structured config.  Fixes #488.
* Reword description of type validation in structured config
> Improve docs regarding interpolations in structured config.  Fixes #488.

- news/418.bugfix
- omegaconf/omegaconf.py
- tests/test_base_config.py
> OmegaConf.to_container() : proper error on invalid input

- news/422.bugfix
- omegaconf/basecontainer.py
- tests/test_merge.py
> Fix ConfigKeyError in some cases when merging lists containing interpolation values

- omegaconf/base.py
- omegaconf/nodes.py
- tests/examples/test_postponed_annotations.py
- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_config_eq.py
- tests/test_create.py
- tests/test_errors.py
- tests/test_get_full_key.py
- tests/test_matrix.py
- tests/test_merge.py
- tests/test_nodes.py
- tests/test_omegaconf.py
- tests/test_serialization.py
- tests/test_to_yaml.py
- tests/test_utils.py
Relative test imports are causing issues in an unnamed monorepo.
> fixed test imports to be absolute

- tests/test_base_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_config_eq.py
- tests/test_create.py
- tests/test_errors.py
- tests/test_get_full_key.py
- tests/test_matrix.py
- tests/test_merge.py
- tests/test_nodes.py
- tests/test_omegaconf.py
- tests/test_select.py
- tests/test_serialization.py
- tests/test_to_yaml.py
- tests/test_utils.py
Relative test imports are causing issues in an unnamed monorepo.
> Test imports 2.0 branch

- docs/source/usage.rst
This is a follow-up to https://github.com/omry/omegaconf/commit/5f471ecbb6105ea5a1f7f4b422e7cd75499f0de8#r46668217
> Document node interpolation (for non-leaf nodes)

- news/524.bugfix
- omegaconf/nodes.py
- tests/test_interpolation.py
- tests/test_matrix.py
> Fix optional flag for interpolated nodes

- docs/notebook/Tutorial.ipynb
- docs/source/config_interpolation.yaml
- docs/source/usage.rst
> documenting relative interpolations

- docs/source/usage.rst
- news/483.feature
- news/554.bugfix
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/nodes.py
- tests/__init__.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_dict.py
- tests/test_compare_dictconfig_vs_dict.py
- tests/test_errors.py
- tests/test_serialization.py
- tests/test_to_yaml.py
> Adding support for bool and float as DictConfig key types

- docs/source/usage.rst
- news/398.feature
- news/548.api_change
- omegaconf/__init__.py
- omegaconf/base.py
- omegaconf/basecontainer.py
- omegaconf/omegaconf.py
- tests/test_to_container.py
> to_container: replace exclude_structured_configs with SCMode

- news/583.api_change
- news/583.bugfix.1
- news/583.bugfix.2
- omegaconf/basecontainer.py
- omegaconf/dictconfig.py
- omegaconf/listconfig.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
> `{Dict,List}Config.{get(),pop()}` now treat `None` like other valid values

- news/589.bugfix
- omegaconf/omegaconf.py
- tests/test_base_config.py
> Nested flag_override now properly restore the orignal state

- news/608.api_change
- news/608.feature
- omegaconf/base.py
- omegaconf/omegaconf.py
- tests/test_interpolation.py
Fixes #608
Best review both commits separately (second one is just moving functions around)
> Deprecate `get_resolver()` and add new `has_resolver()`

- benchmark/benchmark.py
- omegaconf/grammar_parser.py
- tests/test_grammar.py
> Fix performance issue when checking for interpolations

- docs/source/usage.rst
Minor edits to the `OmegaConf.to_container` section of the documentation.
> Docs: edit "Utility functions" & make "Debugger integration" toplevel

- docs/source/usage.rst
Followup to https://github.com/omry/omegaconf/pull/602#issuecomment-799542205.
> docs: configs should be directed acyclic graphs

- docs/source/usage.rst
- omegaconf/omegaconf.py
- tests/interpolation/test_custom_resolvers.py
- tests/test_grammar.py
Fixes #370
Note: there is no additional news item because there is a already an item referring to #426, which also includes a pointer to #370 (at the end). Since these changes are pretty small I'm not sure it's worth making them more prominent in the news, so @omry let me know how you feel about that.
> Improvements to the `register_new_resolver()` API

- omegaconf/_impl.py
- tests/test_omegaconf.py
responding to feedback on #639
> Resolve updates

- benchmark/benchmark.py
- docs/notebook/Tutorial.ipynb
- docs/source/usage.rst
- news/179.feature
- omegaconf/_utils.py
- omegaconf/base.py
- omegaconf/grammar/OmegaConfGrammarLexer.g4
- omegaconf/grammar/OmegaConfGrammarParser.g4
- omegaconf/grammar_parser.py
- omegaconf/grammar_visitor.py
- omegaconf/omegaconf.py
- tests/test_errors.py
- tests/test_grammar.py
- tests/test_select.py
- tests/test_update.py
- tests/test_utils.py
> Support for getitem notation

- omegaconf/omegaconf.py
This speeds up benchmark/benchmark.py::test_update_force_add by ~50%.
This is the optimization from https://github.com/omry/omegaconf/pull/665#discussion_r608598996
I might do the other one later (no time right now)
> Optimization in update()

- benchmark/benchmark.py
- docs/source/usage.rst
- news/667.api_change
- omegaconf/basecontainer.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_config.py
- tests/test_errors.py
- tests/test_readonly.py
- tests/test_update.py
closes #667
See issue for some context.
> OmegaConf.update merge flag is now True by default

- news/579.bugfix
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_errors.py
- tests/test_omegaconf.py
> Prevent assigning None to non-optional element_type

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- tests/structured_conf/test_structured_config.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_errors.py
My PR #696 was incorrect.
This PR will revert #696. 
Reopens issue #579 and closes #704.
> Revert PR#696

- omegaconf/dictconfig.py
- tests/test_basic_ops_dict.py
- tests/test_basic_ops_list.py
- tests/test_errors.py
- tests/test_readonly.py
> add __delattr__ to DictConfig

- omegaconf/grammar_parser.py
- tests/test_grammar.py
Fixes #715
Do we need a news item for bugfixes in-between RC releases?
Note: the diff is easier to read when [ignoring whitespaces](https://github.com/omry/omegaconf/pull/716/files?w=1)
> Ensure the grammar cache is thread-safe

- news/769.feature
> news fragment for clear_resolver

- MANIFEST.in
- news/772.misc
- setup.py
Cherry picked diff #776 from `2.1_branch` to `master`
> fix packaging issue on master branch

- NEWS.md
- news/501.feature
- news/772.misc
- omegaconf/version.py
> update NEWS.md and version.py for 2.1.1 release

- tests/test_utils.py
This minor test update is a follow-up to [this comment](https://github.com/omry/omegaconf/pull/845#discussion_r786824277)
> Minor update to test_utils.py

- docs/source/structured_config.rst
This PR adds to the documentation on enum-typed nodes.
> add doc on conversion to enum from qualified string

- tests/test_nodes.py
I think these `noqa` comments are not necessary.
Let's see if the CI passes...
> remove unneeded noqa: F601 comments

- tests/test_basic_ops_list.py
Adding some test cases to `tests/test_basic_ops_list.py`.
> add str/bool cases to test_basic_ops_list:test_append_convert

- tests/structured_conf/test_structured_config.py
> minor: remove duplicated test case

- omegaconf/basecontainer.py
A minor improvement to typing of BaseContainer._resolvers
> Minor: Mark BaseContainer._resolvers as ClassVar

- omegaconf/version.py
> bump dev version: 2.2.0.dev2

- tests/test_update.py
CI is failing on `master` branch.
> fix failing CI

- noxfile.py
> jupyter notebook CI: ignore ResourceWarning

- tests/test_basic_ops_list.py
> refactor test_basic_ops_list.py

- tests/test_grammar.py
minor diff due to `black` update
> run updated `black` version on codebase

- noxfile.py
> cherry-pick noxfile update to fix ci

- news/817.bufgix
> add news fragment for issue #817

- tests/test_serialization.py
> improve type hint in test_serialization.py

- tests/structured_conf/test_structured_config.py
> rename variable in tests

- omegaconf/_impl.py
- tests/structured_conf/data/attr_classes.py
- tests/structured_conf/data/dataclasses.py
- tests/structured_conf/test_structured_basic.py
> fix OmegaConf.resolve for interpolation to structured conf

- tests/test_nodes.py
- tests/test_utils.py
This PR consolidates several related tests that were spread out in different files
> minor: consolidate _node_wrap tests

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_basic.py
- tests/test_utils.py
> Prevent OmegaConf.structured(...) from mutating its input

- omegaconf/_utils.py
- omegaconf/basecontainer.py
- omegaconf/listconfig.py
- omegaconf/omegaconf.py
- tests/structured_conf/test_structured_basic.py
- tests/test_utils.py
This reverts commit c8fc02c6de51220703e46138ea166ad58667a037.
> Revert "Prevent OmegaConf.structured(...) from mutating its input (#909)"

- docs/source/structured_config.rst
This PR improves formatting in `docs/source/structured_config.rst`.
> fixup structured_config.rst code snippets

- tests/test_nodes.py
> add cases to tests/test_nodes.py

- NEWS.md
- news/144.feature
- news/427.feature
- news/460.feature
- news/547.api_change
- news/573.api_change
- news/608.api_change
- news/698.api_change
- news/720.feature
- news/736.feature
- news/743.api_change
- news/769.feature
- news/789.bugfix
- news/799.feature
- news/831.bugfix
- news/844.feature
- news/848.api_change
- news/849.feature
- news/97.feature
- omegaconf/version.py
This PR syncs NEWS.md from the new `2.2_branch` to the `master` branch and bumps the version on `master` to `2.3.0.dev0`.
> master branch: sync NEWS.md, bump -> v2.3.0.dev0

- omegaconf/version.py
This PR bumps `2.2_branch` to `v2.2.2.dev0`.
> bump version -> v2.2.2.dev0

- news/934.bugfix
- omegaconf/nodes.py
- tests/structured_conf/test_structured_config.py
- tests/test_nodes.py
- tests/test_utils.py
Cherry-picked from diff #941 (closing #934).
> cherry pick Path->str conversion

- README.md
Adding links to release notes and source code for `2.2_branch`.
> Update README.md for OmegaConf v2.2

- omegaconf/omegaconf.py
- tests/__init__.py
- tests/test_create.py
- tests/test_utils.py
This PR cherry picks #944 to `2.2_branch`.
> 2.2_branch: list/tuple subclass: behavior same as 2.1_branch

- docs/source/conf.py
> 2.1_branch: Fix CI

- docs/source/conf.py
> 2.2_branch: Fix CI

- tests/structured_conf/test_structured_config.py
Bug #884 was fixed by PR #913.
This PR adds a test to make sure that bug #884 will *stay* fixed.
> add test closing #884

- omegaconf/omegaconf.py
CI fix, cherry-picked from #989.
> lint: line length (2.2_branch)

- omegaconf/version.py
> Bump version -> v2.3.0.dev2

- news/880.feature
> news fragment for #880

- docs/source/how_to_guides.rst
- docs/source/index.rst
- docs/source/usage.rst
Add how_to_guides.rst
Here's a screenshot:
> docs how to guides

- .readthedocs.yaml
- docs/source/conf.py
- docs/source/how_to_guides.rst
- noxfile.py
- requirements/dev.txt
- requirements/docs.txt
Cherry pick #1045 and #1047 to 2.3_branch
> cherry-pick: docs use sphinx-tabs for yaml/python

- omegaconf/listconfig.py
- tests/test_merge.py
Removing an unused parameter from a test
> rm unused parameter from test

- docs/source/api_reference.rst
Testing if this PR triggers an automatic readthedocs.io build via webhook.
> test commit to trigger readthedocs build

- news/1091.misc
- news/1114.misc
Followup to PR #1114 correcting the news file.
> news file followup to PR #1114

- build_helpers/build_helpers.py
- noxfile.py
We're seeing some CI failures in another PR #1201.
This PR is an attempt to fix those failures.
- Modify noxfile code related to pytest warning suppression
- Rm unused mypy ignore comment
> Try to fix CI
