omegaconf/omegaconf.py

When comparing numpy array to string, numpy throws a warning. See: https://stackoverflow.com/a/46721064/9654319

Fix numpy warning if val is numpy array

---

omegaconf/omegaconf.py
tests/test_interpolation.py

Really useful project!
This helps keep parity when you merge multiple configs, one that defines
values as bools in YAML and another one that interpolates these boolean
values from the environment
I have noticed that you have added other `NodeTypes` but haven't used them, so please tell me if this is not how you planned this to happen and I'll update accordingly.

If passing an env var value that can be parsed with yaml, pass it through parsed

---

docs/source/usage.rst
omegaconf/config.py
omegaconf/omegaconf.py
tests/test_base_config.py
tests/test_interpolation.py

This PR adds the ability to pass in 0 or more arguments to resolvers:
```
${foo:}               # zero arguments
${foo:a}              # one argument (currently supported)
${foo:a,b,..,n}       # n arguments
```

Support passing variable number of arguments to resolvers.

---

omegaconf/dictconfig.py
tests/test_basic_ops_dict.py

implemented __contains__ in DictConfig.
A key is in a dict if there is an associated value that is not None and does not result in a MissingMandatoryValue or KeyError exceptions.

implemented and tested __contains__ (key in cfg)

---

.circleci/config.yml
news/66.removal
noxfile.py
omegaconf/config.py
omegaconf/omegaconf.py
tests/test_serialization.py

deprecated Config.save() in favour of OmegaConf.save()

---

news/39.bugfix
news/72.bugfix
omegaconf/config.py
tests/test_readonly.py
tests/test_update.py

* Read-only list can no longer be replaced with command line override 
* Config.merge_with_dotlist() now throws if input is not a list or tuple of strings

Read-only list can no longer be replaced with command line override 

---

omegaconf/omegaconf.py
tests/test_interpolation.py

No longer using yaml parser to decode environment variables as it causes issues for strings that are not valid yaml.

env resolver no longer parsing yaml strings 

---

news/95.bugfix
omegaconf/config.py
tests/test_create.py

Fixes #95 by removing timestamp implicit resolver in yaml loader. 
```
In [3]:  OmegaConf.from_dotlist(["my_date=2019-11-11"])
Out[3]: {'my_date': '2019-11-11'}
```

Fix disable automatic conversion of date strings in yaml decoding

---

omegaconf/basecontainer.py
tests/test_struct.py

merge_with_dotlist now throws AttributeError if in struct mode and key is not found

merge_with_dotlist now throws AttributeError

---

news/159.bugfix
omegaconf/omegaconf.py
tests/test_serialization.py

Addresses issue #159
Test for pathlib.Path added.

Add support for pathlib.Path

---

news/174.bugfix
omegaconf/basecontainer.py
omegaconf/dictconfig.py
tests/test_basic_ops_dict.py
tests/test_struct.py

Fix a bug that caused Attribute error when accessing a config in struct mode with get() providing a None default
Closes #174

Fixed attribute error when accessing config in struct mode with get and with default of None

---

news/184.feature
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
omegaconf/nodes.py
omegaconf/omegaconf.py
tests/test_base_config.py
tests/test_config_eq.py
tests/test_merge.py

This changes the semantics of merging into node interpolation, enabling a node we are interpolating into to act as a "by value" template.
```python
c1 = {"n": {"a": 10}, "i": "${n}"}
c2 = {"i": {"b": 20}}
c3 = {"n": {"a": 10}, "i": {"a": 10, "b": 20}}
assert OmegaConf.merge(c1, c2) == c3
```
fixes #184

Merge respects node interpolation

---

omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/omegaconf.py
tests/__init__.py
tests/test_base_config.py
tests/test_basic_ops_dict.py
tests/test_config_eq.py
tests/test_utils.py

to_container now properly handles DictConfig and ListConfig that represents a missing value, a None value or an interpolation.

To container fixes

---

news/257.bugfix
omegaconf/_utils.py
tests/test_serialization.py

This adds a custom constructor to the YAML loader created in
get_yaml_loader() so that duplicate keys in the YAML file result in a
PyYAML ConstructorError.
Duplicate keys are not allowed as per the YAML spec but are silently
ignored by PyYAML. This is a potential source of hard-to-detect errors
due to misconfigurations. It has been reported several times in the
PyYAML issues, e.g. https://github.com/yaml/pyyaml/issues/165. The
specific fix here was proposed at https://gist.github.com/pypt/94d747fe5180851196eb.

Report errors when loading YAML files with duplicate keys

---

omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/nodes.py
omegaconf/omegaconf.py
requirements/dev.txt
requirements/lint.txt
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_errors.py
tests/test_readonly.py

Allow merge into config with readonly node if they are not changed

---

news/269.bugfix
news/271.bugfix
omegaconf/basecontainer.py
tests/__init__.py
tests/test_merge.py

Merge into missing

---

news/289.bugfix
omegaconf/_utils.py
tests/test_create.py

Closes #289
By adding a class wrapper for yaml.SafeLoader it solves the problem.
Added test and news report.

Fixes #289 Omegaconf chaging SafeLoader

---

news/297.bugfix
omegaconf/omegaconf.py
tests/test_serialization.py

Loading an empty YAML file now returns an empty DictConfig

---

news/296.bugfix
omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/listconfig.py
omegaconf/omegaconf.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py

When representing Float/Boolean/Int as string and then printing with pretty causes the string to be printed without quotes which can cause problems.
Added tests in both DictConfig and ListConfig.
Added news file.
Closes #296 .

Fix #296 Float/Boolean/Int represented as string, pretty.

---

news/306.bugfix
omegaconf/basecontainer.py
tests/test_merge.py

Merging a missing list onto an existing one makes the target missing

---

tests/test_base_config.py

Not sure it's the best way to fix #314 but at least it avoids adding noise when testing locally :)

Fix nox session coverage-3.6 with Python <= 3.6.3

---

docs/notebook/Tutorial.ipynb
docs/source/usage.rst
news/308.feature
omegaconf/__init__.py
omegaconf/_utils.py
omegaconf/base.py
omegaconf/errors.py
tests/test_interpolation.py
tests/test_utils.py

This is to fix #100 
Doc and tests are missing, I'm aware of it, I wanted to first get feedback on the implementation itself, in case there'd be any major concern.
The main parsing logic is in `_evaluate_complex()`, it's actually not too complex since we can sequentially iterate on all characters in the string and evaluate interpolations in the order we encounter their end `}`. So the core logic is simple but there are still "details" to be addressed (see concerns below).
This is not a super efficient implementation: (i) there are many string copies in the process, and (ii) the worst case complexity is quadratic in case of deep nesting (Edit: not anymore, see comment below). That being said, I don't expect it to be a real issue in the large majority of practical use cases.
A few potential …

Implement nested interpolations

---

docs/notebook/Tutorial.ipynb
docs/source/structured_config.rst
docs/source/usage.rst
news/263.removal
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/omegaconf.py
tests/examples/test_dataclass_example.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py
tests/test_nodes.py
tests/test_to_yaml.py

Closes #263 .
Pretty() instance method is changed to OmegaConf.to_yaml() static method.

OmegaConf.to_yaml 

---

docs/notebook/Tutorial.ipynb
docs/source/usage.rst
news/308.feature
omegaconf/__init__.py
omegaconf/_utils.py
omegaconf/base.py
omegaconf/errors.py
tests/test_interpolation.py

This reverts commit 7d5f8fca92119119c3a41c38daddf254d4cf07a5.
This functionality is being re-implemented with a proper parser generator
and will come in OmegaConf 2.1
cc @odelalleau

Revert "Implement nested interpolations (#308)"

---

news/327.bugfix
omegaconf/listconfig.py
tests/__init__.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_errors.py
tests/test_merge.py

Closes #327 .
I added test for testing ListConfig and DictConfig(only ListConfig failed). Also added a test for test_merge and one for test_error with the introduced new error to fix this issue.
I followed the same strategy to validate_set as dictconfig.py config with `issubclass(value_type, target_type)`.

fix merge list of structured class

---

.gitignore
CONTRIBUTING.md
tests/test_base_config.py

Reverts mac specific hacks to tests and adds instructions on how to install supported Python versions on Mac.
cc @odelalleau - Please try to follow the instructions and make sure you can make it work before I land this.
I got it to work and it's actually quiet nice.

Reverts mac specific coverage hacks

---

.pre-commit-config.yaml
omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/omegaconf.py
tests/structured_conf/test_structured_config.py
tests/test_base_config.py
tests/test_basic_ops_dict.py
tests/test_config_eq.py
tests/test_errors.py
tests/test_matrix.py
tests/test_merge.py
tests/test_omegaconf.py
tests/test_utils.py

Change version and reformat with the new changes. 
I changed to 20.8b1 version in black because as mentioned in https://github.com/psf/black/issues/420:
> Notably it gives the illusion that the latest version is being used but in reality it uses the version at install time.

Change black version in .pre-commit-config.yaml.

---

news/364.bugfix
omegaconf/base.py
tests/test_interpolation.py

Fix #364
NB: I didn't understand the motivation for the two lines I removed -- but tests still passed after removing them so I guess it should be ok :)

Properly crash when trying to access child of a value node

---

news/390.feature
omegaconf/_utils.py
omegaconf/version.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py

SC fields without a value are not convereted to omegaconf.MISSING

---

news/394.bugfix
omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py
tests/test_merge.py

1. fixes new bug with allow_objects not being respected in merge.
2. closes #394

Merge allow objects

---

news/386.bugfix
omegaconf/basecontainer.py
omegaconf/dictconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

When a ValueNode was being assigned to a DictConfig it was never check if it was a valid type(if DictConfig had an element_type). Moreover looking at the bug I replaced the test for Str2IntWithStrField because it should raise an error. 
Closes #386 .

Fix bug assigning structured classes of different element_type in dictconfigs #386

---

news/411.api_change
omegaconf/_utils.py
tests/structured_conf/test_structured_config.py

Structured Configs with nested Structured config field that does not specify a default value are now
interpreted as MISSING (`???`) instead of auto-expanding

Not auto-expanding nested Structured Configs without a default value

---

news/407.bugfix
omegaconf/_utils.py
omegaconf/basecontainer.py
tests/__init__.py
tests/test_serialization.py

Closes #407 .
Now when pickling structured configs ref_types like `Dict[kt, vt]` and `List[vt]` are transformed to `Dict` and `List` respectively and then reconstructed when loading.
The reason behind this is for ensuring that the config doesn't get modified after pickle.
```python
dict_ = copy.copy(self.__dict__)
dict_["_metadata"] = copy.copy(dict_["_metadata"])
```

Fix #407 Subscripted Dict and List unable to be pickled on python 3.6.

---

news/433.bugfix
omegaconf/listconfig.py
tests/structured_conf/test_structured_config.py

Fix #433 bug where ListConfig is modified after assignment of wrong value.

---

omegaconf/dictconfig.py

In #434 we noticed that a shallow copy wasn't needed.

remove shallow copy in previous_content

---

omegaconf/base.py
tests/test_errors.py
tests/test_interpolation.py

When using ${a.b}, if `a` is not a container node, the previous code was failing with an obscure AssertionError.
This commit was originally the first commit in the stack in #321 but was unrelated to other changes in that PR, so it makes more sense to create a different PR.
I don't think it's worth adding an issue and a news item for this (since it seems pretty minor) but let me know if I should.
Note: the motivation for adding `test_assertion_error()` is that otherwise coverage would drop below 100%.

More explicit error when trying to access the child of non-container node

---

news/450.bugfix
omegaconf/dictconfig.py
tests/test_basic_ops_dict.py
tests/test_serialization.py

Closes #450 .
When copying a dictconfig it copied its `_content` which is a dict, that means that ValueNodes is kept as before(shallow copy of a dict).

Fix bug #450 where DictConfig's copy didn't properly copy primitive types.

---

.pre-commit-config.yaml
news/473.feature
omegaconf/_utils.py
omegaconf/omegaconf.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

Adds provisional support for typed dict.
Closes #473

Tentative support for TypedDict

---

.gitignore
benchmark/benchmark.py
news/477.feature
noxfile.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
requirements/dev.txt
tests/test_base_config.py
tests/test_basic_ops_list.py
tests/test_create.py

Closes #267
Closes #477
1. Adds a new benchmark using [pytest-benchmark](https://pytest-benchmark.readthedocs.io/en/latest/index.html).
Currently it tests creation from dict and from DictConfig. Notably creation from DictConfig is 5 times slower and needs some work.
The benchmark is executed in nox.
To run it manually:
```
$ pytest benchmark/benchmark.py
```
2. Fixed a several bugs with shallow copy
3. Added some more tests ensuring deepcopy semantics.
Optimizations:
1. Added flags cache. This improves initialization time from a large dict in the benchmark from 600ms to 450ms.
It also slows down the already slow the initialization from a large DictConfig from 1300ms to 1500ms, but this one needs more work anyway.
2. Optimized deepcopy for DictConfig (creation speedup from a large …

Benchmark and fixes

---

CONTRIBUTING.md
benchmark/benchmark.py
docs/source/usage.rst
news/482.feature
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/omegaconf.py
requirements/dev.txt
tests/test_base_config.py
tests/test_merge.py

Closes #482
Add support for another variant of merge which is about 15 times faster in a benchmark.
The difference is that this version destroys the input configs, so it should only used if the input configs should not be used after the merge call.
It's working by not copying input nodes on set, this making the input configs inconsistent (their nodes parent no longer points to the original config, so interpolations and other things will fail for them.
Another difference than the normal merge is that this merge variant is merging directly into the first config node, eliminating the need for another whole deepcopy.
`pytest benchmark/benchmark.py --benchmark-sort=name  -k merge`:

Unsafe merge

---

news/486.bugfix
omegaconf/base.py
tests/test_merge.py

Fix merge into a custom resolver node that raises an exception

---

omegaconf/basecontainer.py

No point in serializing the flags cache, it can just be re-initialized lazily later on access.
Serializing it is also wasteful and breaking protocol compatibility.

Fixed to not serialize flags cache when pickling

---

news/496.bugfix
omegaconf/basecontainer.py
omegaconf/omegaconf.py
tests/test_merge.py

Merge element type

---

omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
omegaconf/nodes.py
omegaconf/omegaconf.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py
tests/test_create.py
tests/test_errors.py
tests/test_merge.py
tests/test_serialization.py
tests/test_utils.py

ref_type was meant to be equivalent to type annotation:
```
x : Foo = Bar()
```
Above, x should have the ref_type Foo.
ref_type is consulted when assigning values to x, to ensure that they are of the right type.
(such assignment results in a runtime exception in OmegaConf).
Over time, ref_type was used for additional things like encoding the key type and element type of a DictConfig.
In addition, for implementation reasons, ref_type of Structured Configs automatically matched the object type:
```
cfg = OmegaConf.create({"user":  User})
```
above, cfg.user has the ref_type User, which means it cannot be assigned anything else.
This is not intentional.
Such behavior is justified using Structured Config:
```python
@dataclass
class Config
user: User = User()
```
but not when using the …

Changing default ref_type to Any

---

news/425.bugfix
omegaconf/dictconfig.py
tests/test_struct.py

DictConfig.get() always returns None for non existing keys

---

news/470.bugfix
omegaconf/_utils.py
tests/test_create.py
tests/test_serialization.py

This adds support for YAML merge tags (<< *ref) while retaining the
sanity check for duplicate keys. Note that the spec for merge keys
(https://yaml.org/type/merge.html) explicitly states that keys in the
current mapping override the ones in the merged mapping. Hence, the
check for duplicates is applied to scalar keys of the current mapping
only.
Fixes #470.

Support YAML merge tags

---

docs/notebook/Tutorial.ipynb
docs/source/usage.rst
news/515.api_change.1
news/515.api_change.2
omegaconf/base.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
tests/test_base_config.py
tests/test_basic_ops_dict.py
tests/test_errors.py
tests/test_interpolation.py
tests/test_omegaconf.py
tests/test_struct.py

Fixes #515.
This is an historical mistake. See #515 for some explanation and migration instructions.

Dict getitem consistency

---

tests/test_errors.py

I noticed that the following are redundant:
assert ex.object_type == expected.object_type
...
if not expected.low_level:
...
if expected.object_type is not None:
assert ex.object_type == expected.object_type

remove duplicated assertion from test_errors.py

---

omegaconf/base.py
omegaconf/dictconfig.py
omegaconf/omegaconf.py
tests/test_basic_ops_list.py
tests/test_errors.py
tests/test_interpolation.py
tests/test_omegaconf.py

Based on comment https://github.com/omry/omegaconf/pull/516#discussion_r571080800
we use a separate exception type `InterpolationResolutionError` to indicate failure of interpolation, instead of using `ConfigKeyError`.

Use interpolation resolution error

---

news/527.api_change
omegaconf/dictconfig.py
tests/test_omegaconf.py

api change: dictconfig.get("missing") returns None

---

benchmark/benchmark.py
news/529.feature
omegaconf/listconfig.py
tests/test_basic_ops_list.py

Speedup from 1200x slower than standard list contains to only 68 times slower (~15x).
Closes #529

Optimizing ListConfig.__contains__

---

benchmark/benchmark.py
news/532.feature
omegaconf/listconfig.py

closes #532
Before, +1000x times slower than native list.
After, #160x times slower than native list.

Optimizing ListConfig iterator

---

tests/test_base_config.py
tests/test_to_container.py

This PR moves the `OmegaConf.to_container` tests from `test_base_config.py` to a new `test_to_container.py` file.
This PR is motivated by https://github.com/omry/omegaconf/pull/503#discussion_r570537028.

Move to_container tests from test_base_config.py to test_to_container.py

---

docs/notebook/Tutorial.ipynb
docs/source/usage.rst

The main purpose is to get (almost) the same content in the docs and in the notebook.
There is also a minor change to the doc on node interpolation, to make
it clearer that we can use them as config objects (they are not plain
Python dictionaries).

Update notebook to synch with the docs

---

news/531.bugfix
news/550.api_change
omegaconf/basecontainer.py
omegaconf/omegaconf.py
tests/test_to_container.py
tests/test_to_yaml.py

enum_to_str: convert enum keys, not just enum values

---

tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py

This PR does not make any major changes -- it is just a refactoring of the `test_structured_basic.py` and `test_structured_config.py` files.
- Replace `import pytest` with `from pytest import fixture, mark, param, raises`
- Factor out a fixture for importing from the correct module:
```python
@fixture(
params=[
"tests.structured_conf.data.dataclasses",
"tests.structured_conf.data.attr_classes",
],
]
)
def module(request: Any) -> Any:
return import_module(request.param)
```

Refactor structured config tests

---

news/563.bugfix
omegaconf/omegaconf.py
tests/test_select.py

Fix handling of `throw_on_missing` flag for `select()` on ListConfig

---

omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
tests/__init__.py
tests/test_merge.py
tests/test_nodes.py
tests/test_utils.py

Closes #566 
sidestep source of https://github.com/facebookresearch/hydra/issues/1285 at the omegaconf level

Workaround for Dataframe object in the config: check whether value is string before mandatory missing check

---

omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
omegaconf/nodes.py

This clears all literal "???" under the omegaconf module except the definition of MISSING.

refactor: clean up MISSING checks

---

news/572.api_change
omegaconf/grammar/OmegaConfGrammarParser.g4
omegaconf/grammar_visitor.py
tests/test_grammar.py

Support and deprecate empty args

---

omegaconf/base.py
tests/test_base_config.py

config flags are currently defined as:
> the value of a config flag is the value set on a node, 
> or the value from the parent node (if there is a parent), otherwise None.
This diff changes the definition to:
> the value of a config flag is the value set on a node, or None if the node is a flags root.
> otherwise, the value from the parent node (if there is a parent), otherwise None.
This means we can now indicate that flag access will not query the parent node for chosen nodes.
For now I am keeping it as an internal API to be used by Hydra config composition:
the hydra node itself is a flags root, meaning it will not be affected by flags set on the user config root.

Introduced flags_root as an internal concept

---

omegaconf/base.py

This is more readable and avoids accessing the dictionary twice

Minor simplification in `_get_node_flag()`

---

news/586.bugfix
omegaconf/dictconfig.py
omegaconf/listconfig.py
omegaconf/omegaconf.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py
tests/test_readonly.py
tests/test_struct.py

Struct assign

---

omegaconf/dictconfig.py
omegaconf/nodes.py
omegaconf/omegaconf.py
tests/test_interpolation.py
tests/test_nodes.py

This PR extracts some of the changes from #578, related to the handling of `None` values.
Note that the test `test_none_value_in_quoted_string` added here is not directly related to these changes (since it worked before this PR too), but it is good to have this test in before #578.

Improved handling of `None` values in node validation

---

omegaconf/grammar/OmegaConfGrammarParser.g4
omegaconf/grammar_parser.py
omegaconf/grammar_visitor.py
tests/test_grammar.py
tests/test_interpolation.py

This enables implementing a form of select with a default value:
Side note, we should rethink support for passing the parent node automatically on demand (`${.}`), it will simplify this use case.
```python
from typing import Any
from omegaconf import OmegaConf
from omegaconf.omegaconf import _EMPTY_MARKER_
yaml = """\
a: 10
no_default: ${oc.select:${.}, a}
not_using_default: ${oc.select:${.}, a, 20}
using_default: ${oc.select:${.}, not_there, 20}
"""
def oc_select(node: Any, key: str, default: Any = _EMPTY_MARKER_):
if default is _EMPTY_MARKER_:
return OmegaConf.select(node, key)
else:
return OmegaConf.select(node, key, default=default)
OmegaConf.register_new_resolver("oc.select", oc_select)
cfg = OmegaConf.create(yaml)
assert cfg.a == 10
assert cfg.no_default == 10
assert …
```

Grammar support for interpolations like ${.}. ${..} etc.

---

docs/source/structured_config.rst
docs/source/usage.rst
news/488.api_change
news/540.api_change
news/540.feature
omegaconf/base.py
omegaconf/dictconfig.py
omegaconf/errors.py
omegaconf/grammar_visitor.py
omegaconf/nodes.py
tests/conftest.py
tests/test_base_config.py
tests/test_interpolation.py
tests/test_matrix.py

Validate and convert interpolation results to their intended type
This PR fixes several issues:
* For nested resolvers (ex: `${f:${g:x}}`), intermediate resolver
outputs (of `g` in this example) were wrapped in a ValueNode just to
be unwrapped immediately, which was wasteful. This commit pushes the
node wrapping to the very last step of the interpolation resolution.
* There was no type checking to make sure that the result of an
interpolation had a type consistent with the node's type (when
specified). Now a check is made and the interpolation result may be
converted into the desired type (see #488).
* If a resolver interpolation returns a dict / list, it is now wrapped
into a DictConfig / ListConfig, instead of a ValueNode. This makes it
possible to generate configs from resolvers (see …

Type validation of interpolations

---

docs/source/usage.rst
news/266.feature
omegaconf/base.py
omegaconf/omegaconf.py
tests/test_interpolation.py

Custom resolvers can now receive optional _parent_ and _root_ parameters.
This is the doc example:
```python
OmegaConf.register_new_resolver(
"sum_friends",
lambda a, b, *, _parent_: _parent_[a] + _parent_[b],
use_cache=False,
)
cfg = OmegaConf.create(
{
"a": {
"b": 1,
"c": 2,
"sum": "${sum_friends:b,c}",
},
}
)
assert cfg.a.sum == 3
```

Support optional _parent_ and _root_ parameters in custom resolvers

---

omegaconf/base.py
tests/test_interpolation.py

It is now an `InterpolationResolutionError` instead of an
`OmegaConfBaseException` (which is not supposed to be raised directly).

Change exception type when dereferencing a node without a parent

---

omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/errors.py
tests/test_errors.py

When there was a cycle when iterating over parents of a node,
`_get_full_key()` would get into an infinite loop.
This commit detects this situation to raise an explicit exception
instead.
In addition, `format_and_raise()` is modified to *not* raise exceptions
when trying to obtain the full key, so as to avoid hiding the original
exception with a different error. Instead, any exception raised when
trying to obtain the full key is displayed on the "full key" line of the
error message.

Avoid infinite loop in `_get_full_key()`

---

omegaconf/base.py
tests/test_interpolation.py

Trying to dereference a node without a parent was raising an
`InterpolationResolutionError` even with `throw_on_resolution_failure`
set to False.
This bug was pointed out in https://github.com/omry/omegaconf/pull/607#discussion_r595485365 and is related to the recent #605.

Do not throw when throw_on_resolution_failure is False

---

docs/source/usage.rst
news/214.feature
pydevd_plugins/__init__.py
pydevd_plugins/extensions/__init__.py
pydevd_plugins/extensions/pydevd_plugin_omegaconf.py
requirements/dev.txt
setup.py
tests/test_pydev_resolver_plugin.py

Closes #214
See included doc for user facing description.
Example:
For this config:
```yaml
simple = OmegaConf.create(
{
"a": "bar",
"inter": "${a}",
"inter2": "foo_${a}",
"inter_error1": "${zzz}",
"inter_error2": "foo_${zzz}",
"missing": "???",
},
)
```
Object inspection with USER flavor:
Object inspection with DEV flavor:
Object inspection with the resolver disabled (default behavior prior to extension):

Pydev.Debugger extension

---

docs/notebook/Tutorial.ipynb
docs/source/env_interpolation.yaml
docs/source/usage.rst
news/230.bugfix
news/445.feature.1
news/573.api_change
news/574.feature
omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/omegaconf.py
tests/test_interpolation.py
tests/test_utils.py

* Restore and deprecate the old `env` resolver for backward
compatibility with OmegaConf 2.0
* The new `oc.env` resolver keeps the string representation of
environment variables, and does not use the cache
* The new `oc.decode` resolver can be used to parse and evaluate strings
according to the OmegaConf grammar
Fixes #383
Fixes #573
Fixes #574
Notes:
* the diff for the notebook can be seen at https://odelalleau.github.io/diff/diff_notebook_decode.html
* the diff of test_interpolation.py is hard to read because there was an indentation change => I created a dummy diff at https://github.com/odelalleau/omegaconf/pull/2/files that doesn't have the indentation change for better readability

Introduce new `oc.env` and `oc.decode` resolvers

---

news/532.misc
omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/listconfig.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py

Closes #613
Second optimization pass.
This is more impressive than the 7.7 -> 8.8x recorded improvement since there seems to be a regression compares to the measurements in #533.
Speed is still not great, but I this is as close as it gets given that we are probably losing a bunch of low level optimization done on native list because we need to unbox primitive items when we iterate.
Comparing `test_list_iter[small_listconfig]` by itself to what is in master shows about 50% speedup:
When it's pitched against the native list iteration it's "only" 130 times slower now, compares to 180 times slower before:
By the way: here is why this is important:
https://twitter.com/jackyliang42/status/1371530444529881094

optimized list iterator some more

---

benchmark/benchmark.py
news/532.misc
omegaconf/_utils.py

Another 20% on top of master by removing a type assertion from _is_missing_literal.

Further speedup of ListConfig iteration

---

news/532.misc
omegaconf/_utils.py

Further speedup of ListConfig iteration.
```
master     now     speedup
test__is_missing_literal                439.6 ns   96.0 ns    4.5x
test__list_iter[small_listconfig]       11.04 us   9.11 us    1.2x
```

optimized _is_missing_literal

---

omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
tests/conftest.py
tests/examples/dataclass_postponed_annotations.py
tests/examples/test_dataclass_example.py
tests/examples/test_postponed_annotations.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/test_base_config.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py
tests/test_config_eq.py
tests/test_create.py
tests/test_errors.py
tests/test_get_full_key.py
tests/test_interpolation.py
tests/test_matrix.py
tests/test_merge.py
tests/test_nodes.py
tests/test_omegaconf.py
tests/test_readonly.py
tests/test_select.py
tests/test_serialization.py
tests/test_to_yaml.py
tests/test_update.py

- Diff 1 : No functional changes. fixing the pytest imports for all tests. Expect minor conflicts because of this for outstanding diffs. 
- Diff 2: Adding better testing to DictConfig items
- calling items() on DictConfig("???") and DictConfig(None) now results in exception similar to what you get when iterating on corresponding ListConfigs. the rest of the changes are tests and updating other code in response to this change.
I think this is not user facing for people using the public API so there is no need for a news fragment or doc change.

DictConfig.items() handles DictConfig(None) and DictConfig("???") consistently with ListConfig

---

omegaconf/omegaconf.py
tests/test_interpolation.py

Some builtin functions like `print()` cannot be inspected.

Avoid crash when registering a non-inspectable resolver

---

omegaconf/omegaconf.py
tests/test_to_container.py

This PR removes the deprecated `exclude_structured_configs` option.
This is a follow-up to #552.
Closes #556.

remove deprecated `exclude_structured_configs` option from `to_container`

---

pydevd_plugins/extensions/pydevd_plugin_omegaconf.py
tests/test_pydev_resolver_plugin.py

Example:
```python
foo = OmegaConf.create({
"list": ListConfig([{"a": 10}]),
"inter": ListConfig("${list}"),
},
)
```
Expanding `foo.inter`, the first element in the list was incorrect.

Fixed container inspection through interpolating

---

omegaconf/grammar/OmegaConfGrammarLexer.g4
tests/test_grammar.py

Related to #634
(though not fixing the exact example from that issue, that also includes an `=` sign that will not be allowed in unquoted strings)

Grammar: allow question marks in unquoted strings

---

docs/source/usage.rst
news/640.feature
omegaconf/_impl.py
omegaconf/omegaconf.py
tests/test_omegaconf.py

Introduces OmegaConf.resolve()
Closes #640

Added OmegaConf.resolve()

---

omegaconf/omegaconf.py
tests/interpolation/test_custom_resolvers.py
tests/test_errors.py
tests/test_matrix.py
tests/test_merge.py
tests/test_select.py

Should be a good time to re-enable this warning now that the `register_new_resolver()` API is finalized.
Note that I updated #426, @omry please have a look to check that it's clear enough. Thanks!

Enable the deprecation warning for `register_resolver()`

---

news/648.bugfix
omegaconf/omegaconf.py
tests/test_create.py

`OmegaConf.create()` now properly sets the parent for string inputs

---

docs/notebook/Tutorial.ipynb

Some doc updates from #606 were not fully ported to the notebook.

Synch notebook with doc

---

omegaconf/omegaconf.py
tests/interpolation/test_interpolation.py
tests/test_select.py

I am not including a news fragment because relative interpolations are new in 2.1.

Fixed OmegaConf.select() with relative keys

---

omegaconf/omegaconf.py
tests/test_select.py

The support added for relative keys in select (#656) was a breaking change.
in 2.0, when select is called on a nested node, it's already relative.
#656 made that select absolute, which is a breaking change.
A non breaking fix is to keep nested selects relative, but add support for relative syntax (specifically for going up the hierarchy).
The resulting behavior is shown below and can be a bit surprising:
```python
from omegaconf import OmegaConf
cfg = OmegaConf.create(
{
"a": {
"b": {
"c": 10,
}
},
"z": 10,
},
)
assert OmegaConf.select(cfg.a, "") == {"b": {"c": 10}}
assert OmegaConf.select(cfg.a, "b") == {"c": 10}
assert OmegaConf.select(cfg.a, ".") == {"a": {"b": {"c": 10}}, "z": 10}
assert OmegaConf.select(cfg.a, ".a") == {"b": {"c": 10}}
assert OmegaConf.select(cfg.a, ".z") == 10
``` …

OmegaConf.select is relative to the node it's called on

---

docs/notebook/Tutorial.ipynb
docs/source/usage.rst
omegaconf/omegaconf.py
tests/interpolation/built_in_resolvers/test_env.py

This changes the behavior of oc.env to convert the input default value to string if it's used (except for None).
Followup: update #573.

oc.env: converts none-string inputs to string instead of raising an exception

---

benchmark/benchmark.py
docs/source/usage.rst
news/664.feature
omegaconf/omegaconf.py
tests/test_update.py

Add force_add to OmegaConf.update(), effectively using open_dict for all nodes along the path

---

omegaconf/_impl.py
omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
pydevd_plugins/extensions/pydevd_plugin_omegaconf.py
tests/interpolation/test_interpolation.py
tests/test_nodes.py

On `master`, the `Node._dereference_node` method returns `Optional[Node]`. This leads to some `assert node is not None` statements in the code (for the benefit of `mypy`).
This PR does two things:
- introduce a new method, `Node._maybe_dereference_node`, which returns `Optional[Node]`
- change the type signature of `_dereference_node` to retrurn `Node` (not optional).
This change lets us delete some of the `node is not None` assertions.
This PR is a followup to https://github.com/omry/omegaconf/pull/502#discussion_r608711688.

Refactoring: `_maybe_dereference_node`

---

docs/source/usage.rst
news/643.feature
omegaconf/base.py
omegaconf/built_in_resolvers.py
omegaconf/omegaconf.py
tests/interpolation/built_in_resolvers/test_dict.py
tests/interpolation/test_custom_resolvers.py

Fixes #643
Better check commits separately: the meaningful one is the [second one](https://github.com/omry/omegaconf/pull/644/commits/5fe304f12e39a68a49db0aa2ceafff6c156424da), the other two are refactor commits with no functional changes.

Add new resolvers `oc.dict.keys` and `oc.dict.values`

---

news/584.bugfix
omegaconf/_utils.py
tests/__init__.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_errors.py

in get_structured_config_data: check for dict subclass data

---

benchmark/benchmark.py
omegaconf/_utils.py
omegaconf/omegaconf.py
tests/__init__.py
tests/test_base_config.py
tests/test_basic_ops_list.py
tests/test_grammar.py
tests/test_omegaconf.py
tests/test_utils.py

This avoids invalidating the flags cache with `force_add=False`.
This gives a ~10% speed-up on the benchmark test_update_force_add that
updates the key ""a.a.a.a.a.a.a.a.a.a.a" (previous benchmark), and a
~50% speed-up on the new (and faster) benchmark that just updates "a".
This commit also fixes an issue with this benchmark, where re-using the
same config across tests was introducing dependencies between tests.
======================
This is the other optimization I had suggested in https://github.com/omry/omegaconf/pull/665#discussion_r608611363
Note: there is still an issue with this benchmark because the large dictconfig is only created once for each test, and re-used across the multiple calls to the function within `benchmark()`. As a result both the flags cache and the config …

Additional optimization to update() without force_add

---

docs/source/conf.py
docs/source/custom_resolvers.rst
docs/source/index.rst
docs/source/usage.rst
news/681.feature
omegaconf/_impl.py
omegaconf/base.py
omegaconf/omegaconf.py
omegaconf/resolvers/oc/__init__.py
omegaconf/resolvers/oc/dict.py
tests/interpolation/built_in_resolvers/test_oc_deprecated.py
tests/test_select.py

1. Refactor docs, moving resolvers to a dedicated page.
2. Adding support for oc.deprecated.
Most of changed lines here are from the docs refactor.
Try to go over it anyway and let me know if you have any feedback.
Closes #681.

oc.deprecated

---

news/678.bugfix
omegaconf/_impl.py
omegaconf/base.py
omegaconf/omegaconf.py
tests/interpolation/test_interpolation.py
tests/test_errors.py
tests/test_select.py

Followup to discussion 678. easier to review individual commits.
1. eliminating redundant tests.
2. Change exception raised when trying to drill into a non-container with select from ConfigKeyError to ConfigTypeError.
3. Change OmegaConf.select to return None if user attempts to drill into a non existing node (into a ValueNode or into None).
Closes #678

678 select

---

omegaconf/base.py
omegaconf/omegaconf.py
omegaconf/resolvers/oc/__init__.py
tests/test_grammar.py

Note that the node is now guaranteed to always be available.
This is my suggestion from https://github.com/omry/omegaconf/pull/679#discussion_r614137195

Optimization to avoid re-fetching the node on each resolver call

---

omegaconf/_impl.py
tests/interpolation/built_in_resolvers/test_dict.py
tests/test_select.py

Fixes #674
Note:
1. I removed a test from `oc.dict.{keys,values}`, was not sure exactly what it was protecting against but it looks like it was depending on some funky logic in select that is not needed by anything else.
2. News fragment is not needed because default value in OmegaConf.select is new in 2.1.

674 select with default

---

omegaconf/omegaconf.py
tests/test_to_container.py

What do we think about removing the `enum_to_str` keyword argument from `OmegaConf.to_object`?
Here is my argument for removal:
- make the public API simpler,
- users can still call `OmegaConf.to_container(..., enum_to_str=True)` if they need it, and
- make sure that the `DictConfig._to_object` method is consistent with the `OmegaConf.to_object` method. Currently, `DictConfig._to_object` calls `BaseContainer._to_content` with `enum_to_str=False`, which will result in an inconsistency if the client calls `OmegaConf.to_object(cfg, enum_to_str=True)`, i.e. we could get some `enum_to_str=True` and some `enum_to_str=False` in the same deserialized object.

to_object no enum_to_str

---

omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/listconfig.py
omegaconf/omegaconf.py
tests/structured_conf/test_structured_basic.py
tests/test_matrix.py
tests/test_omegaconf.py
tests/test_utils.py

Deprecate OmegaConf.is_optional

---

omegaconf/base.py
omegaconf/grammar/OmegaConfGrammarLexer.g4
omegaconf/grammar/OmegaConfGrammarParser.g4
omegaconf/grammar_visitor.py
tests/test_grammar.py

Quoted values are now identified through lexer modes, which removes the
need for escaping quotes in nested interpolations.
Fixes #615

New syntax for nested quoted values

---

pyproject.toml

I've added a '-Werror' flag to pytest's ini options.
I expect that the CI tests will fail (#710 is fixing some warnings that are currently issued).

Pytest to fail on warnings

---

omegaconf/base.py
omegaconf/nodes.py
omegaconf/omegaconf.py
tests/interpolation/test_custom_resolvers.py
tests/interpolation/test_interpolation.py
tests/test_nodes.py

Fixes #666
This is a first stab at it in order to ground discussions. I did a bit more than the "bandaid" fix I had suggested in #666, to get a cleaner behavior (at the expense of passing around a new "can_be_interpolation" flag).
In this first version I only included this flag in `AnyNode` and `StringNode` so as to somewhat limit potential side effects, though it's a bit ugly because it leaks into `ValueNode._set_value_impl()`. I wouldn't mind making it an attribute of `ValueNode`, which could serve as a first step towards caching the interpolation status in the future, but I preferred to wait until we'd discuss it.

Fix crash with "interpolation-like" strings from interpolations

---

docs/source/usage.rst

`SCMode.DICT` is not mentioned in the docs currently.
Since it is the default option for the `to_container(..., structured_config_mode)` keyword, I think it would be good to mention it.

Mention SCMode.DICT in the docs.

---

omegaconf/basecontainer.py
omegaconf/dictconfig.py

This PR does two things:
- change return type of `DictConfig.keys` from `Any` to `AbstractSet[DictKeyType]`, and
- ensure that `DictConfig.keys` always returns an `AbstractSet`. Previously, an empty `list()` was returned in the case where the the config was an interpolation/missing/none.

typing: DictConfig.keys to return AbstractSet

---

omegaconf/basecontainer.py
tests/test_errors.py

Previously the following examples either gave an `AssertionError` or returned a config object with bad metadata:
```python
OmegaConf.create( {}, {"a", "b"})  # bad metadata
OmegaConf.create({"zz": 10}, {"a", "b"})  # used to raise AssertionError
OmegaConf.create(Dog, {"a", "b"})  # used to raise AssertionError
```
Now all three examples raise `ConfigTypeError`.

BaseContainer: error if `parent` has wrong type

---

news/601.bugfix
omegaconf/listconfig.py
tests/test_basic_ops_dict.py
tests/test_basic_ops_list.py

Closes #601
Not worried about perf:
This is something we are already doing for DictConfig, and ListConfig is not used nearly as much.

ListConfig append deepcopies input config nodes

---

omegaconf/dictconfig.py
omegaconf/listconfig.py
tests/test_config_eq.py

Closes #741.
I've added an additional branch to each of `DictConfig.__eq__` and `ListConfig.__eq__`:
```
if self._is_missing:
return _is_missing_literal(other)
```
This allows for `assert DictConfig("???") == "???"` and `assert ListConfig("???") == "???"`.

Make missing {Dict,List}Config compare equal to "???"

---

news/743.api_change
omegaconf/_utils.py
omegaconf/nodes.py
tests/__init__.py
tests/interpolation/test_interpolation.py
tests/structured_conf/test_structured_basic.py
tests/test_basic_ops_list.py
tests/test_errors.py
tests/test_utils.py

Closes #743 
The `ValidationError` raised by `IntegerNode` and `FloatNode` now contains the type of the value that triggered the error.

IntegerNode/FloatNode ValidationError message: include value type

---

omegaconf/basecontainer.py
tests/__init__.py
tests/test_merge.py

Closes #751.
Previously (in OmegaConf 2.0) it was possible to merge a list into a ListConfig(None) that had `ref_type==Tuple[int, ...]` and `is_optional=True`.
In 2.1, this was no longer possible.
This PR patches the regression.

Fix regression:  merging list into optional tuple

---

omegaconf/base.py
omegaconf/nodes.py
tests/__init__.py
tests/interpolation/test_interpolation.py
tests/test_errors.py
tests/test_nodes.py

This PR improves error messages raised when interpolating to `None` from a node whose `ref_type` is not optional.
- The interpolation key is now included in the error message.
- The error message now includes the `ref_type` of the target field.
- The error message no longer uses the word "assign", which was misleading because (semantically) assignment is not taking place when an interpolation is dereferenced.
If this PR is merged into `master`, I'll plan to cherry pick the updates and open a similar PR against the OmegaConf `2.1_branch`.
Closes #753.

Improve error message for InterpolationValidationError

---

requirements/base.txt

PEP440 requires >=5.1.0 instead of >=5.1.*

Fix PyYAML dependency version sintax

---

tests/test_errors.py

This PR should fix the pypy error message that is causing https://github.com/conda-forge/omegaconf-feedstock/pull/19 build to fail.

Update regular expression so tests will pass on pypy

---

docs/source/custom_resolvers.rst
docs/source/grammar.rst
docs/source/index.rst
docs/source/usage.rst
omegaconf/grammar/OmegaConfGrammarParser.g4

Some "design choices" I made, happy to discuss them here:
* Not dumping the whole set of parser rules as is done in [Hydra's documentation](https://hydra.cc/docs/advanced/override_grammar/basic): this is because it would be pretty much unreadable with the current documentation formatting (in particular due to the limited width). Instead, I chose to focus on a few relevant excerpts, and link to the file if someone wants to see the whole thing
* Making a few simplifications (not mentioning all details), in order to (hopefully) keep it digestible
I'm requesting reviews for diverse people to get feedback both from those familiar vs unfamiliar with it.
For ease of reviewing I suggest you build it locally:
```
cd docs && make html && open build/html/index.html
```

Add documentation for the OmegaConf grammar

---

omegaconf/_utils.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

This PR closes #817.
- https://github.com/omry/omegaconf/commit/78da5506e6772a6ed377d1763a4419ec9ef0f4ce:
Write failing tests based on #817.
As of this commit, the following two tests fail:
```
pytest tests/structured_conf/test_structured_config.py -k 'dataclasses-dict_overwrite_missing'
pytest tests/structured_conf/test_structured_config.py -k 'dataclasses-list1_overwrite_missing'
```
- https://github.com/omry/omegaconf/commit/9bbaadc11891e5991075952d0812ff3b508cce99:
Support defining default_factory in child structured config. Tests pass.

Fix `default_factory` support in structured config subclasses

---

omegaconf/listconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

This PR is to close #827.
- https://github.com/omry/omegaconf/commit/9970a3d9cdf5f541fd478070e1cafb94c7b7f49e: Write failing tests based on #827.
As of this commit, the following four tests fail:
```text
- tests/structured_conf/test_structured_config.py::TestConfigs::test_list_of_objects_missing[dataclasses]
- tests/structured_conf/test_structured_config.py::TestConfigs::test_list_of_objects_missing[attr_classes]
- tests/structured_conf/test_structured_config.py::TestConfigs::test_assign_list_of_objects[dataclasses]
- tests/structured_conf/test_structured_config.py::TestConfigs::test_assign_list_of_objects[attr_classes]
```
- ~https://github.com/omry/omegaconf/commit/75369399a43a9c107470194c3b0ca57a666c5348~ https://github.com/omry/omegaconf/pull/828/commits/7e5ed4d2b9c45b776de7cad4976601a …

Allow assignment of MISSING in List[Structured]

---

pyproject.toml

A recently-released version of the black formater has exposted a typo in our pyproject.toml file.
This typo is not a problem on the master branch because it was fixed in #800.

2.1_branch CI: typo in black config regex

---

tests/structured_conf/test_structured_config.py

PR #558 introduced the `module` fixture into test_structured_config.py.
This PR converts a straggler function that slipped through in #558 to use the `module` fixture as well.

Refactor test_structured_config.py: followup to #558

---

docs/source/structured_config.rst

Closes #833
Docs update: In the structured config examples, import statements are made more obvious.

structured config docs: explicit import statements

---

tests/test_utils.py

This PR adds tests for the [`_utils.get_list_element_type`](https://github.com/omry/omegaconf/blob/0bf9e8fdd65f374b7c0601aab69061df0f0bf583/omegaconf/_utils.py#L608) and [`_utils.get_dict_key_value_types`](https://github.com/omry/omegaconf/blob/0bf9e8fdd65f374b7c0601aab69061df0f0bf583/omegaconf/_utils.py#L617) functions.
Edit:
The second commit adds tests for nested container types.

Add tests for `get_list_element_type` and `get_dict_key_value_types`

---

news/849.feature
omegaconf/listconfig.py
tests/test_basic_ops_list.py

Closes #849.
```python
>>> cfg = OmegaConf.create([1, 2])
>>> [3] + cfg
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: can only concatenate list (not "ListConfig") to list
```
```python
>>> cfg = OmegaConf.create([1, 2])
>>> [3] + cfg
[3, 1, 2]
```

Implement `ListConfig.__radd__`

---

tests/examples/test_dataclass_example.py

This PR adds a "string" case to the structured config convert-on-assignment test.

add `str` test in test_dataclass_example.py:test_conversions

---

tests/test_grammar.py

Version 22.1.0 of the [black](https://github.com/psf/black) formatter
now [normalizes string prefix order](https://github.com/psf/black/pull/2297).
This PR updates our codebase so that CI will not fail with this new version of black.

Fix CI for black==22.1.0

---

tests/interpolation/test_interpolation.py
tests/test_basic_ops_list.py
tests/test_nodes.py
tests/test_utils.py

This PR rounds out the tests for Enum types.
It also removes a bit of dead code (`Enum2`) from `tests/test_nodes.py`.

improve Enum-type test coverage

---

tests/test_nodes.py

This PR converts a test in `test_nodes.py` to use `pytest.param` instead of a bare tuple.
This was part of my work in finalizing the BytesNode PR #845 which I've extracted here.

add pytest.param ids to test_node.py:test_legal_assignment

---

.pre-commit-config.yaml
build_helpers/build_helpers.py
news/848.api_change
noxfile.py
omegaconf/dictconfig.py
pydevd_plugins/__init__.py
pydevd_plugins/extensions/__init__.py
requirements/dev.txt
setup.cfg
tests/test_serialization.py

To conform with the `MutableMapping` API, The `DictConfig.items` method now returns an object of type `ItemsView`, and `DictConfig.keys` will now always return a `KeysView`.

Unpin mypy

---

NEWS.md
news/736.feature

Ease future updates from towncrier by using standard
news format for feature 736

adjust 736 news to use standard mechanism

---

news/789.bugfix
omegaconf/_utils.py
omegaconf/dictconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/test_to_container.py
tests/test_utils.py

This PR improves `OmegaConf.to_object` so that structured configs with `init=False` fields can be handled.
This comes up for example when calling `to_object` on a structured config generated by [`hydra_zen.builds`](https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.builds.html) (as such structured configs use an `init=False` field for the `_target_` key).
Here is a demo of the use-cases enabled by this PR:
```python
from dataclasses import dataclass, field
from omegaconf import DictConfig, OmegaConf
@dataclass
class Foo:
x: str = field(init=False)
y: str = field(init=False, default="default")
z: str = field(init=False)
def __post_init__(self) -> None:
self.z = "set_by_post_init"
cfg1 = OmegaConf.structured(Foo)
assert OmegaConf.is_missing(cfg1, "x")
assert cfg1.y == …
```

`OmegaConf.to_object` handling of `init=False` fields

---

omegaconf/omegaconf.py

This update adds `Any` to the union return type for
`OmegaConf.to_container`.
**Motivation**
`OmegaConf.to_container` may return a dataclass instance in the case
where the `structured_config_mode` parameter passed to `to_container`
has value `SCMode.INSTANTIATE`. This is the case in which the
`Any` return type annotation applies.

Update the return type annotation for OmegaConf.to_container

---

news/831.bugfix
omegaconf/_utils.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

This PR modifies the `_utils.get_dataclasses_data` function to fix two closely-related bugs, #830 and #831.
- `get_dataclass_data(obj)` now branches based on whether its input is a dataclass vs a dataclass instance. This closes [#830](#830).
- `get_dataclass_data` no-longer branches based on whether the attribute lookup `getattr(obj, fieldname)` is equal to the missing string `"???"`. This closes [#831](#831).

`get_dataclass_data`: branch on dataclass vs dataclass instance

---

omegaconf/omegaconf.py
tests/test_nodes.py
tests/test_utils.py

The arguments `type_` and `ref_type` to the `_node_wrap` function are redundant.
This PR removes the `type_` argument.
I chose to keep `ref_type` instead of `type_` for consistency with other parts of the codebase.

remove redundant arg from _node_wrap

---

omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/nodes.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py
tests/test_basic_ops_dict.py
tests/test_create.py
tests/test_serialization.py
tests/test_utils.py

Renaming some internal functions for consistency
- rename `_utils._is_union` -> `_utils.is_union_annotation`
- rename `_utils.valid_value_annotation_type` -> `_utils.is_valid_value_annotation`
- rename `_utils.is_primitive_type` -> `_utils.is_primitive_type_annotation`
The above renamings are for consistency with the functions `is_container_annotation`, `is_dict_annotation`, `is_list_annotation`.
- rename `_utils.get_ref_type` -> `_utils.get_type_hint`:
this is for consistency with other uses of variable name `ref_type` in the codebase. Normally `ref_type` in OmegaConf's codebase refers to a type annotation that has had `typing.Optional` stripped away, and `type_hint` refers to a type annotation that *is* possible wrapped in `typing.Optional[...]`. 
I'll squash these into a single commit …

refactoring: rename some functions

---

news/608.api_change
omegaconf/omegaconf.py
tests/interpolation/test_custom_resolvers.py

Users should use OmegaConf.has_resolver() instead.
Was slated for removal in 2.2
The deprecation was handled in issue #608
This addresses issue #821

remove support for OmegaConf.get_resolver()

---

news/547.api_change
omegaconf/omegaconf.py
tests/test_matrix.py
tests/test_omegaconf.py

Was slated for removal in 2.2
The deprecation was handled in issue #547
This addresses issue #821

remove support for OmegaConf.is_none()

---

news/698.api_change
omegaconf/omegaconf.py
tests/test_omegaconf.py

Was slated for removal in 2.2
The deprecation was handled in issue #698
This addresses issue #821

remove support for OmegaConf.is_optional()

---

docs/source/structured_config.rst
news/144.feature
omegaconf/__init__.py
omegaconf/_impl.py
omegaconf/_utils.py
omegaconf/base.py
omegaconf/basecontainer.py
omegaconf/dictconfig.py
omegaconf/listconfig.py
omegaconf/nodes.py
omegaconf/omegaconf.py
tests/__init__.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_base_config.py
tests/test_basic_ops_dict.py
tests/test_errors.py
tests/test_get_full_key.py
tests/test_grammar.py
tests/test_matrix.py
tests/test_merge.py
tests/test_nested_containers.py
tests/test_nodes.py
tests/test_omegaconf.py
tests/test_serialization.py
tests/test_to_container.py
tests/test_unions.py
tests/test_utils.py

This PR implements support for unions of primitive types (i.e. unions of `int`, `float`, `bool`, `str`, `bytes`, and `None`).
A few notes:
- `Union` can be freely mixed with `Optional` and `None`. For example, all of the following are equivalent:
- `Optional[Union[int, str]]`
- `Union[Optional[int], str]`
- `Union[int, str, None]`
- `Union[int, str, type(None)]`
- Containers of unions (e.g. `List[Union[int, str]]`, or `Dict[int, Union[str, bytes]]`) *are* supported.
- Unions of containers (e.g. `Union[List[str], Dict[str, str], MyStructuredConfig]`) *are not yet* supported. This will come in a followup PR.
Here is a demo of the API:
```python
from omegaconf import OmegaConf, ValidationError
from dataclasses import dataclass
from typing import Union
from pytest import raises
@dataclass …
```

preliminary UnionNode implementation

---

news/934.bugfix
omegaconf/nodes.py
tests/structured_conf/test_structured_config.py
tests/test_nodes.py
tests/test_utils.py

allow conversion Path -> str

---

omegaconf/resolvers/oc/dict.py
tests/interpolation/built_in_resolvers/test_oc_dict.py

Fix `oc.dict.values` behavior for relative dotpaths

---

omegaconf/resolvers/oc/dict.py
tests/interpolation/built_in_resolvers/test_oc_dict.py

Cherry picked from #946 to `2.1_branch`.

2.1_branch: Fix oc.dict.values behavior for relative dotpaths

---

omegaconf/resolvers/oc/dict.py
tests/interpolation/built_in_resolvers/test_oc_dict.py

Cherry picked from #946 to `2.2_branch`.

2.2_branch: Fix oc.dict.values behavior for relative dotpaths

---

news/973.api_change
omegaconf/_utils.py
omegaconf/dictconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_nested_containers.py
tests/test_utils.py

This closes #973.
The root cause of #973 was that `tuple` was being treated differently from `Tuple`.
This PR is a move towards treating `tuple` and `Tuple` in the same way when the appear in type annotations, and likewise for `dict`/`Dict` and `list`/`List`.

type hints: treat dict/Dict/tuple/Tuple/list/List uniformly

---

news/963.bugfix
omegaconf/_utils.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py

This PR closes #963.
DictConfigs based on Attr classes now support forward references (whereas before only dataclasses supported forward references).

use typing.get_type_hints for attr classes

---

news/950.bugfix
omegaconf/listconfig.py
tests/test_basic_ops_list.py

* omegaconf/listconfig.py (__setitem__): Operate on a copy
so any changes due to validation errors etc. are discarded.
Fixes issue #950

ensure atomic updates for ListConfig sliced assignment (#950)

---

news/991.bugfix
omegaconf/_utils.py
omegaconf/omegaconf.py
tests/__init__.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py
tests/test_utils.py

Three commits:
- [make _utils.type_str robust against unsupported types](https://github.com/omry/omegaconf/pull/993/commits/8749a7f43179f828ee71286dc18c959ddd9d5b2a)
- [Handle unsupported type annotation gracefully](https://github.com/omry/omegaconf/pull/993/commits/2098b51132f268af4c4dc94c6b087173bdf066fa)
- [revert allow_objects behavior for unsupported annotations](https://github.com/omry/omegaconf/pull/993/commits/ae9a0d32463b4294b4d40af93046931ea93f7fbf)
The second commit closes #991. The third commit reverts a regression in behavior for the `allow_objects` flag (details below).
Running the following example script, here is a comparison of before vs after this diff:
```python
from dataclasses import dataclass
from typing import Sequence
from omegaconf import OmegaConf
@dataclass …
```

Improve handling of illegal type annotations

---

docs/source/structured_config.rst
news/950.bugfix
news/963.bugfix
news/991.bugfix
omegaconf/_utils.py
omegaconf/listconfig.py
omegaconf/omegaconf.py
tests/__init__.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py
tests/test_basic_ops_list.py
tests/test_utils.py

This PR cherry-picks several commits from `master` to `2.2_branch`.
- Update structured config docs: mention `bytes` (#947)
- use typing.get_type_hints for attr classes (#979)
- ensure atomic updates for ListConfig sliced assignment (#950)
- make _utils.type_str robust against unsupported types ([#993](https://github.com/omry/omegaconf/pull/993))
- Handle unsupported type annotation gracefully ([#993](https://github.com/omry/omegaconf/pull/993))
- revert allow_objects behavior for unsupported annotations ([#993](https://github.com/omry/omegaconf/pull/993))

Cherry pick from master to 2.2 branch

---

docs/source/structured_config.rst
news/984.feature
omegaconf/_utils.py
omegaconf/dictconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/test_structured_config.py
tests/test_to_container.py

This PR implements the `"omegaconf_ignore"` metadata inspection proposed in #984.
TODO:

skip structured conf fields with "omegaconf_ignore" metadata

---

.pre-commit-config.yaml

The `git://` protocol is deprecated.

Fix broken URL in .pre-commit-config.yaml

---

tests/structured_conf/test_structured_config.py
tests/test_utils.py

On Windows, the addresses of objects are for whatever reason represented with capital hexadecimals. This is causing [tests to fail](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=553925&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213) on conda-forge.
Note: I don't have Windows myself, so I can't test this, but it seems straightforward enough.

Fix some tests which fail on Windows

---

docs/source/custom_resolvers.rst
docs/source/grammar.rst
docs/source/structured_config.rst
docs/source/usage.rst

This prevents the title of each page from appearing in its own table of
contents.

docs: use :local: directive for page TOCs

---

benchmark/benchmark.py
omegaconf/_utils.py
setup.cfg
tests/examples/dataclass_postponed_annotations.py

Mypy no longer officially supports python3.6.
Updating the `python_version` setting in the mypy config
avoids some errors that were only showing up when mypy was
installed with python3.6.
Fixes the test failure [here](https://app.circleci.com/pipelines/github/omry/omegaconf/2823/workflows/1e961ad3-1a9f-4ddd-92df-5a3e873e67c6/jobs/10776?invite=true#step-103-364).

mypy: update python_version and type: ignore comments

---

docs/source/api_reference.rst
docs/source/conf.py
docs/source/index.rst
omegaconf/omegaconf.py

- modify OmegaConf docstrings to use standard rst
- docs: api_reference.rst via sphinx autodoc
Below is a screenshot of the new API Reference docs page:

Docs: add API Reference page

---

noxfile.py

This causes nox to error out if tests cannot be run due to a missing python interpreter.

set nox error_on_missing_interpreters=True

---

omegaconf/dictconfig.py

DictConfig._get_node never returns a list

simplify DictConfig._get_node return type

---

omegaconf/omegaconf.py

The `OmegaConf.clear_resolvers` method was not showing up on the API Reference page of OmegaConf's website.
After adding a docstring, sphinx autodoc picks up on the method.

Add docstring for `OmegaConf.clear_resolvers` method

---

.circleci/config.yml

The [`circleci/python`](https://hub.docker.com/r/circleci/python) images are outdated and do not support python3.11.
The images [`cimg/python`](https://hub.docker.com/r/cimg/python) are to supersede the `circleci/python` images.

CI: use docker image cimg/python, not circleci/python

---

.circleci/config.yml
docs/source/structured_config.rst
news/feature.1023
noxfile.py
setup.py
tests/__init__.py
tests/examples/test_dataclass_example.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/data/dataclasses_pre_311.py
tests/structured_conf/test_structured_basic.py
tests/structured_conf/test_structured_config.py
tests/test_utils.py

This PR updates OmegaConf's tests and metadata for compatibility with python3.11.
There are no changes to the omegaconf source code.
The changes to the test are motivated by [python3.11 dataclasses dropping support for mutable default arguments](https://docs.python.org/3/whatsnew/3.11.html#dataclasses). This means dataclasses with mutable default arguments must use `default_factory`.
I've updated the dataclasses in the test suite to use `default_factory`, and I've added a file `tests/structured_conf/dataclasses_pre_311.py` that contains old-style dataclasses that do *not* use `default_factory` for mutable dataclass defaults. This pre_311 file is run only when python version < 3.10.
Commits:
- tests/structured_config module fixture: use pytest.param
- test dataclass with mutable default: …

support python3.11

---

noxfile.py
pyproject.toml

Recent versions of pytest no longer (by default) add pwd to the
PYTHONPATH. This affects module discovery and can lead to errors like
`No module named 'tests.conftest'` when running pytest locally. This
commit modifies pyproject.toml configuring pytest's pythonpath to
include pwd by default.

pytest: explicitly add pwd to pythonpath

---

tests/test_to_container.py

This PR adds a regression test for integration between the
`OmegaConf.{to_container,to_object}` methods and the `"allow_objects"` flag.
Specifically, we test that calling `OmegaConf.{to_container,to_object}` on a
config that contains objects will results in a container that contains the same
objects.

regression test: to_container supports allow_objects

---

omegaconf/version.py

Dev version 2.3.0.dev2 has been [released to pypi](https://pypi.org/project/omegaconf/2.3.0.dev2/).
This PR bumps to v2.3.0.dev3.

Bump version -> v2.3.0.dev3

---

docs/source/conf.py
docs/source/how_to_guides.rst
requirements/dev.txt

Update code examples from our [How-To Guides](https://omegaconf.readthedocs.io/en/2.3_branch/how_to_guides.html) docs page to use [Sphinx tabs](https://sphinx-tabs.readthedocs.io/en/latest/).
Before:
After:
Todo after merge:

docs how-to guide: use sphinx-tabs for yaml/python

---

.readthedocs.yaml
noxfile.py
requirements/dev.txt
requirements/docs.txt

Follow-up to #1045 to rectify failing readthedocs.io build.
Here's the output from the failed build:
```
/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v1.8.6
loading translations [en]... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/omegaconf/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinx_tabs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/omegaconf/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main …
```

sphinx-tabs followup: readthedocs install requirements/docs.txt

---

requirements/dev.txt

Some CI tests were failing because the `attrs` dependency was not installed by `noxfile.py`.
This PR addes `attrs` to `requirements/dev.txt` so that the tests will run.

include attrs dependency in requirements/dev.txt

---

noxfile.py

Pin the version of `setuptools` installed in `noxfile.py` to work around https://github.com/omry/omegaconf/issues/1068.
Since the `DeprecationWarnining` that's causing CI failure is emitted by a 3rd
party dependency of `setuptools`, this failure mode should resolve itself when
some future version of `setuptools` is released. At that time, we can remove
the pin introduced by this PR.

pin setuptools to avoid DeprecationWarning

---

noxfile.py

This is a followup to https://github.com/omry/omegaconf/pull/1069
that accomodates old versions of python ( python3.6 ).

Change noxfile.py setuptools pin from ==66 to <=66

---

noxfile.py

The lint session is giving errors with python3.6.
Specifically, mypy is giving errors with 3.6 that do not
show up with later python versions.
Python3.6 has reached end of life and mypy no longer officially
supports 3.6, so I'm removing the 3.6 lint job from OmegaConf CI.

Skip lint nox session for python3.6

---

requirements/dev.txt

CI lints for python3.7 were failing due to an issue with flake8 (related
to https://github.com/python/importlib_metadata/issues/406); see the
example test failure below. The failure is resolved by ensuring that
the installed version of flake8 is >= 4.0.
<details>
<summary>
Example test failure
</summary>
```text
nox > [2023-04-14 23:08:38,999] Running session lint-3.7
nox > [2023-04-14 23:08:39,000] Creating virtual environment (virtualenv) using python3.7 in .nox/lint-3-7
nox > [2023-04-14 23:08:39,252] python -m pip install --upgrade 'setuptools<=66' pip
nox > [2023-04-14 23:08:43,005] python -m pip install -r requirements/dev.txt -e .
nox > [2023-04-14 23:09:01,123] mypy . --strict --install-types --non-interactive
nox > [2023-04-14 23:09:16,755] isort . --check
nox > [2023-04-14 …
```

pin flake8 >= v4

---

tests/test_basic_ops_dict.py

There was a lint error in the tests:
```
tests/test_basic_ops_dict.py:276: error: Keywords must be strings  [misc]
Installing missing stub packages:
/home/circleci/project/.nox/lint-3-10/bin/python -m pip install types-Pygments types-colorama types-setuptools
Found 1 error in 1 file (checked 81 source files)
```
The problem is, that mypy detects the dict unpacking operator `**` in the function call as syntax error. So I adjusted the test, that the unpacking is still tested, but it don't happen in the function call anymore.
This is by the way a common requested feature / bugfix in mypy.
References:
* https://stackoverflow.com/questions/47632128/how-to-get-mypy-to-accept-an-unpacked-dict
* https://github.com/python/mypy/issues/5869
* https://github.com/python/mypy/issues/10023

tests: fix lint error in tests

---

omegaconf/listconfig.py

* removed a `# type: ignore` comment to satisfy mypy
---

fix: remove unused mypy ignore-tag

---

noxfile.py
pyproject.toml

Fixes #1100
The fix is similar to what was done in https://github.com/facebookresearch/hydra/pull/2696, instead of pinning a specific version of setuptools as in #1068
I'll mark this PR as draft since I still need to check if #1069 can be reverted now.
[Update: I double checked and we can indeed revert #1069 now, so adding it to this PR]

Fix pytest error due to deprecation warning

---

omegaconf/version.py

Bumping the OmegaConf dev version following upload of the `v2.4.0.dev0` prerelease to pypi.org:
https://pypi.org/project/omegaconf/2.4.0.dev0/

bump version -> `v2.4.0.dev1`

---

.circleci/config.yml
.pre-commit-config.yaml
.readthedocs.yaml
CONTRIBUTING.md
docs/source/structured_config.rst
docs/source/usage.rst
news/1109.api_change
noxfile.py
omegaconf/_utils.py
omegaconf/basecontainer.py
omegaconf/omegaconf.py
omegaconf/version.py
requirements/base.txt
requirements/dev.txt
setup.cfg
setup.py
tests/examples/dataclass_postponed_annotations.py
tests/examples/test_postponed_annotations.py
tests/test_base_config.py
tests/test_basic_ops_list.py
tests/test_grammar.py
tests/test_nodes.py
tests/test_omegaconf.py
tests/test_serialization.py
tests/test_utils.py

Fixes #1108
This PR updates pre-commit hooks to the latest current versions of isort / black / flake8 / mypy, and ensures we can run all these tools in the repository without any complaint.

Update pre-commit hooks and drop support for Python 3.6 & 3.7

---

.readthedocs.yaml

Work in progress to fix issues with readthedocs build.
Context:

add required `build.os` key to .readthedocs

---

.readthedocs.yaml

Currently readthedocs is broken due to a missing dependency on java.
Readthedocs supports using the `asdf` tool to isntall utilities such as java (see [here](https://github.com/readthedocs/readthedocs.org/issues/10346#issuecomment-1576570469)).
Closes #1141.

readthedocs: use asdf to provide java for building wheel

---

.readthedocs.yaml

This is a follow-up to PR #1142 that changes the `.readthedocs` config file.
Rather than using the `build.commands` key to install java, we use `build.jobs.post_system_dependencies`.
The problem with the previous approach is that `build.command` overrides all other build steps performed by readthedocs, which we do not want.

readthedocs: install java via post_system_dependencies hook

---

omegaconf/listconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/data/dataclasses_pre_311.py
tests/structured_conf/test_structured_basic.py

This PR closes #1005, fixing a bug where a validation error was raised
when an interpolation points to a structured config from within a typed
list.
```python
from dataclasses import dataclass, field
from omegaconf import MISSING, OmegaConf
@dataclass
class User:
name: str = MISSING
@dataclass
class Config:
user: User = User("John")
users: list[User] = field(default_factory=lambda: ["${user}"])
cfg = OmegaConf.structured(Config)
OmegaConf.resolve(cfg)
print(cfg)
```
BEFORE
------
```text
$ python repro.py
Traceback (most recent call last):
...
omegaconf.errors.ValidationError: Invalid type assigned: str is not a subclass of User. value: ${user}
full_key: users[0]
reference_type=List[User]
object_type=list
```
AFTER
-----
```text
$ python repro.py
{'user': {'name': 'John'}, 'users': …
```

Fix interpolation to structured config from within typed list

---

news/1150.feature
omegaconf/_utils.py

`yaml.CSafeLoader` is **significantly** faster. However, it is not always available. The proposed change is to use it whenever it is available with a fall back to `yaml.SafeLoader` (current loader).
Yes
No additional tests required, current tests should cover yaml being parsed correctly.
What issue does this PR fix? Use https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to link this PR to a corresponding issue.
Fixes #1149 
-

Use CSafeLoader when possible

---

CONTRIBUTING.md

Motivated by https://github.com/omry/omegaconf/pull/1150#issuecomment-1894115443

Add contributor documentation for important components of a PR

---

omegaconf/_utils.py
omegaconf/dictconfig.py
tests/structured_conf/data/attr_classes.py
tests/structured_conf/data/dataclasses.py
tests/structured_conf/data/dataclasses_pre_311.py
tests/test_to_container.py
tests/test_utils.py

`attrs` classes automatically alias any fields with a leading underscore to a stripped version in that class's `__init__()`.
So, the class
```python
@attr.s
class Foo():
_bar: int = attr.ib(default=0)
```
has an `__init__()` that looks like:
```python
def __init__(self, bar):
self._bar = bar
```
---
This PR changes the structured config instantiation behavior to take aliases into account, when setting up the params for an `__init__()`.
Test `test_leading_underscore_fields()` added.
Fixes #1063

fix: `SCMode.INSTANTIATE` for attrs fields with aliases/leading "_"

---

omegaconf/version.py

This PR bumps the dev version of OmegaConf. I'll publish v2.4.0.dev3 to PyPI shortly.

bump version -> v2.4.0.dev3

---

.coveragerc

code coverage CI is failing.
This PR attempts to fix that.
It seems there were two problems with the .coveragerc file:
- when running `coverage report`, the `run.omit` setting in `.coveragerc` was not being picked up. I moved the contents of `run.omit` to `report.omit`.
- The omission pattern `*tests*` was not excluding the tests folder form coverage. I changed `*tests*` to `*/tests/*``.
Yes
Verify coverage now succeeds on CI, and that coverage is still measured for the desired omegaconf source directory.

Modify .coveragerc to fix CI coverage
